# contoh buat ngecek status apache

---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: ngecek status apache
        command: service httpd status
        args:
          warn: no
        changed_when: false

      - name: this will not fail
        command: /bin/false
        ignore_errors: yes