# instal-servis di webserver dan loadbalancer

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: instal apache
        yum: name=httpd state=present
      - name: Pastikan apache starts
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become : true
    tasks:
      - name: instal multi servis di webserver
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Pastikan apache starts
        service: name=httpd state=started enabled=yes