# setting up load balancernya

---
    - hosts: loadbalancers
      become: true
      tasks:
        - name: Mbikin template
          template:
            src: ../config/lb-config.j2
            dest: /etc/httpd/conf.d/lb.conf
            owner: bin
            group: wheel
            mode: 064
          notify: restart si apache

      handlers:
        - name: restart si apache
          service: name=httpd state=restarted